### PR TITLE
allow for optional chain parameters

### PR DESCRIPTION
**Pull request by johncantrell97**
LSPS2 users currently do not need to track the chain and therefore integration is slightly complicated by requiring ChainParameters.

Until LSPS2 also requires chain tracking we should make this optional.

### CODE REVIEW

**Review by tnull — APPROVED** [review]
Yeah, makes sense. We should eventually document what implementations require what parameters, but that should probably be part of an interface rework.

Landing this for now.

**Comment by tnull** [comment]
Ah, wait, CI is failing due to missing `cargo fmt` (@johncantrell97)

**Comment by johncantrell97** [comment]
Thanks, fixed formatting.

**Comment by johncantrell97** [comment]
@tnull thanks, fixed formatting.

**Pull request merged**
