### PR TITLE
Add missing error handling

### PR DESCRIPTION
**Pull request by johncantrell97**
We are missing a lot of the actual error codes/responses that the specification specifies.  This PR attempts to add support for the missing ones.

At the moment it's just the two get_info errors.

### CODE REVIEW

**Comment by tnull** [comment]
This needs rebase now that #20 was merged.

**Review by tnull — COMMENTED** [review]
Second commit LGTM, will review closer once #22 lands. Note that the first commit might become unnecessary due to #39.

**Comment by tnull** [comment]
Needs a rebase now that #22 landed.

**Comment by johncantrell97** [comment]
rebased

**Review by tnull — APPROVED** [review]

**Pull request merged**
