### PR TITLE
Add integration test utils, first LSPS2 integration test

### PR DESCRIPTION
**Pull request by tnull**
Here, we add some integration test utils and add an initial integration test that covers the LSPS2 invoice generation flow up to creating a new invoice. In the future we'll extend that to create a full-cycle test.

However, as this is already quite a bit of code, extending it to a full-cycle test will happen in a follow-up PR.

### CODE REVIEW

**Comment by tnull** [comment]
Rebased for LDK v0.0.123.

@johncantrell97 Would be great to get some intial review on this.

**Comment by johncantrell97** [comment]
This looks fine to me, I don't really have any comments to add.  It seems like most of the stuff in common is directly from ldk, right?

Nice that you're able to use the library in this modular way to pipe the request/responses in and out without any changes.

**Review by johncantrell97 — APPROVED** [review]

**Comment by tnull** [comment]
> This looks fine to me, I don't really have any comments to add. It seems like most of the stuff in common is directly from ldk, right?

Yes, mostly stolen from the `BackgroundProcessor` tests, but deleted a lot of unnecessary code and modified some other parts.

> Nice that you're able to use the library in this modular way to pipe the request/responses in and out without any changes.

Yep!

**Comment by tnull** [comment]
Fixed MSRV CI, going ahead and merge this for now. We'll interate on the test (utils) in the future anyways.

**Pull request merged**
